kind: pipeline
type: kubernetes
name: foo

steps:
- name: Docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: craftingit/healthchecks-docker
    auto_tag: true