kind: pipeline
type: kubernetes
name: foo

steps:
- name: Docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: craftingit/healthchecks-docker
    auto_tag: true

trigger:
  event:
  - push
  - pull_request
  - tag

---
kind: pipeline
type: kubernetes
name: kube-linter-docker-updates

steps:
- name: update dockerfile
  image: craftingit/ci-tools-docker
  commands:
    - bash .ci/updater.sh
    
- name: push commit
  image: appleboy/drone-git-push
  settings:
    remote: git@github.com:CraftingITde/healthchecks-docker.git
    ssh_key:
      from_secret: GITHUB_SSH_KEY
    remote_name: origin
    branch: master
    local_ref: master

trigger:
  event:
  - cron